#!/bin/bash

if [[ $(id -u) != 0 ]]; then
	clear
    whiptail --title "error" --msgbox "please root run" 8 78 
	exit 1
fi

if [ ! -f "/opt/dt" ]; then
  apt -y install locales

  dpkg-reconfigure locales

  touch /opt/dt

fi

export LC_ALL=zh_CN.UTF-8

bash <(wget --no-check-certificate -qO- https://storage.rinvay.co/Dt/dt_ct_ist)

